### ISSUE TITLE
[Feature Request] - Order our lists

### ISSUE THREAD

**Issue by Ziloxeur** [Karitham/WaifuBot#51]
**Is your feature request related to a problem? Please describe.**
No, it's a feature that could help everybody while searching someone in your list. It could be nice if there was a command to order our lists by name(alphabetic order)/anime (alphabetic order)/ make a list with only our favorites ones.

**Describe the solution you'd like**
w.list name/anime and w.favorite add id. You can check your favorite list by using w.listfavorite (w.lf) or w.favoritelist (w.fl)

**Describe alternatives you've considered - optional**
There could be a maximum characters in your favorite list based on your total number of waifu (15%, 100 waifu = 15 favorite)

**Comment by LaneSh4d0w** [comment]
Easy FR, we need to use https://docs.mongodb.com/manual/reference/operator/meta/orderby/ for that.

**Comment by Karitham** [comment]
Since this is possible with the [GUI](https://github.com/go-waifubot/waifugui), I'm closing. If you have any opinions on sorting and ordering there, please raise an issue there.

List navigation in discord is a pain, and will never be nice, because discord isn't great at showing such a huge amount of data.
