### ISSUE TITLE
[Bot Permission Changes] - Give WaifuBot the ability to interact with threads

### ISSUE THREAD

**Issue by LaneSh4d0w** [Karitham/WaifuBot#85]
**Is your feature request related to a problem? Please describe.**
It is easier for Discord users to create threads when interacting with the bot, in case they're trading or doing some other interactions. Per https://discord.com/developers/docs/topics/threads, it is now possible for Bots to read and create threads, and also send, modify, and delete messages inside the threads.

**Comment by Karitham** [comment]
The /command bot is already able to answer in threads, and the regular (message event) bot is going to be deprecated, as per #78 and discord's request.

The public instance of the bot is already available and implements all features of the current bot except `drops`, `claims` and `trending` (which isn't really used, so that one is not a priority).

If you cannot use /commands in your server, make sure the permissions given to the bot are right (you can ensure this by trying to reinvite the bot to the server).
If it is still not working, please open another issue, related to that
