### ISSUE TITLE
[Feature Request] - add new command using the "/"

### ISSUE THREAD

**Issue by HidekiItami** [Karitham/WaifuBot#88]
Lack of "/" commands.
Saddly when the commands "W.p W.g W.c" are down you can't switch to commands by /(something)
Like a /profil, /give or /claim. Like for the /roll

**Comment by Karitham** [comment]
The corde branch, as well as the public bot both support slash commands, unfortunately I'm taking a while to implement the final parts -> drop and claims, because it requires either a bit more infra, or some database changes which I don't have time to do yet.

I hope to get a chance in the next few weeks, but until then, gotta use the corde branch by itself

**Comment by Karitham** [comment]
all current commands (except trending because nobody used it) are now implemented on the slash command bot and the message command bot is deprecated (as in, not active anymore, and won't be in the future)
